spring:
  flyway:
    placeholders:
      dbUser: HotWheels
      appUser: admin
      appPassword: $2a$10$4zde0tFyTP.gtAh4.ULvseAlAJBd.5MbNf8OxMSzO1rF01AX6xcU.
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sharedDataDB
    username: HotWheels
    password: transporter
